# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: La Iberia del siglo XXI
author: Diego
author_link: http://diegocollado.net
author_description: 
email: diego@laiberia.net
description: > # this means to ignore newlines until "baseurl:"
  La Iberia renace en el nuevo siglo como un espacio digital de comentario
  político y cultural.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dieguitocollado.github.io/laiberia2" # the base hostname & protocol for your site

# Picturefill
# A responsive image polyfill: http://scottjehl.github.io/picturefill/
picturefill: false

# Typography
# To use, publish a kit and enter the ID here. If you do not wish to use Typekit,
# leave this ID blank
typekit_kit_id: kwf5dox

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed
