baseURL = "https://jolly-haibt-937465.netlify.com/"
languageCode = "es-es"
title = "La Iberia del siglo XXI"
theme = "basics"

[params]
  AuthorName = "LaIberia.net"
  ListOfFoo = ["foo1", "foo2"]
  SidebarRecentLimit = 5
  Subtitle = "Nace un nuevo espacio liberal en la web."

[permalinks]
  post = "/:year/:month/:title/"