baseURL = "https://www.laiberia.net"
languageCode = "es-es"
title = "La Iberia del siglo XXI"
theme = "basics"

[params]
  AuthorName = "Diego"
  SidebarRecentLimit = 5
  Subtitle = "Nace un nuevo espacio liberal en la web."

[permalinks]
  post = "/:year/:month/:title/"