baseURL = "https://jolly-haibt-937465.netlify.com/"
languageCode = "es-es"
title = "La Iberia del siglo XXI"


[params]
  AuthorName = "Jon Doe"
  GitHubUser = "spf13"
  ListOfFoo = ["foo1", "foo2"]
  SidebarRecentLimit = 5
  Subtitle = "Hugo is Absurdly Fast!"
  theme = basics

[permalinks]
  post = "/:year/:month/:title/"